version: '2'
services:
  oneoff:
    build: ./server
    volumes:
      - ./server:/code
    depends_on:
      - db
  web:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./server:/code
    depends_on:
      - db
  db:
    image: postgres
